### ISSUE TITLE
new package: squashfs-tools

### ISSUE THREAD

**Issue by philipgiuliani** [nanobox-io/nanobox-packages#3]
I need squashfs-tools to generate a firmware for nerves.
See: https://hexdocs.pm/nerves/installation.html#linux

I'm not sure if ssh-askpass is also required. I'll just use `mix firmware.image` to generate an image instead of burning it directly. So probably I'll not need it.

**Comment by notxarb** [comment]
I just created the squashfs package, it should have the mksquashfs and unsquashfs utilities
